### ISSUE TITLE
website linking to thematic/NA/NA/NA

### ISSUE THREAD

**Issue by r2evans** [rstudio/thematic#118]
The website is currently providing a link to a nonexistent "Browse source code" link: `https://rstudio.github.io/thematic/NA/NA/NA/`

![image](https://user-images.githubusercontent.com/5815808/151673834-2625145b-2d82-4341-9370-73f268f6cbe4.png)

(FF96 on win11)

**Comment by cpsievert** [comment]
Pretty sure this is fixed
