### ISSUE TITLE
Provide a thematic_set() or similar

### ISSUE THREAD

**Issue by cpsievert** [rstudio/thematic#12]
To make it easier to restore the old theme (and, if there was no old theme, disable). Something like:

```r
thematic_set <- function(theme) {
  if (!length(theme)) {
    return(thematic_off())
  }
  do.call(thematic_on, theme)
}
```

Then, it'll be easier to cleanup after yourself:

```r
old_theme <- thematic_on(...)
on.exit(thematic_set(old_theme))
```

**Comment by schloerke** [comment]
maybe `thematic_set_theme()`?

I find `set` and `on` to be too similar in name / purpose
