### ISSUE TITLE
Pattern matching in registering Google fonts

### ISSUE THREAD

**Issue by yixuan** [rstudio/thematic#120]
The [current code](https://github.com/rstudio/thematic/blob/main/R/gfonts.R#L48-L53)

```r
font_file <- function(variant) {
  dir(
    cache_dir, full.names = TRUE,
    pattern = paste0(variant, "\\.ttf$")
  )
}
```

will match both `italic.ttf` and `bolditalic.ttf` if `variant` is `"italic"`, thus passing a length-two vector to `systemfonts::register_font()` or `sysfonts::font_add()`. The fix is also simple:

```r
font_file <- function(variant) {
  dir(
    cache_dir, full.names = TRUE,
    pattern = paste0("^", variant, "\\.ttf$")
  )
}
```

**Comment by savemark** [comment]
Oh yes, this is probably what causes the follwing warning I get when using 
`thematic_shiny(font = "auto")`

`Warning in check_font_path(italic, "italic") :
  'italic' should be a length-one vector, using the first element`
