### ISSUE TITLE
Error : thematic doesn't (yet) support the 'httpgd' graphics device (Github Codespace)

### ISSUE THREAD

**Issue by jfulponi** [rstudio/thematic#143]
## Describe the problem

Error : thematic doesn't (yet) support the 'httpgd' graphics device. I'm working in a GitHub Codespace, knitting a RMarkdown.

```r
# Include a minimal and reproducible example here
# If you don't know what that means, please see https://www.tidyverse.org/help

library(ggplot2)
thematic::thematic_rmd(font = "auto")

ggplot(mpg, aes(displ, hwy)) +
  geom_point() + geom_smooth()

```
`
Error : thematic doesn't (yet) support the 'httpgd' graphics device. Please report this error to https://github.com/rstudio/thematic/issues/new
`

### Session Info

<details>
<pre><code>
r$> devtools::session_info() 
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16)
 os       Ubuntu 22.04.3 LTS
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2023-08-30
 pandoc   3.1.1 @ /usr/local/bin/pandoc

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cachem        1.0.8   2023-05-01 [1] RSPM (R 4.3.0)
 callr         3.7.3   2022-11-02 [1] RSPM (R 4.3.0)
 cli           3.6.1   2023-03-23 [1] RSPM (R 4.3.0)
 colorspace    2.1-0   2023-01-23 [1] RSPM (R 4.3.0)
 crayon        1.5.2   2022-09-29 [1] RSPM (R 4.3.0)
 curl          5.0.2   2023-08-14 [1] RSPM (R 4.3.0)
 devtools      2.4.5   2022-10-11 [1] RSPM
 digest        0.6.33  2023-07-07 [1] RSPM (R 4.3.0)
 dplyr       * 1.1.2   2023-04-20 [1] RSPM (R 4.3.0)
 ellipsis      0.3.2   2021-04-29 [1] RSPM (R 4.3.0)
 fansi         1.0.4   2023-01-22 [1] RSPM (R 4.3.0)
 farver        2.1.1   2022-07-06 [1] RSPM (R 4.3.0)
 fastmap       1.1.1   2023-02-24 [1] RSPM (R 4.3.0)
 forcats     * 1.0.0   2023-01-29 [1] RSPM (R 4.3.0)
 fs            1.6.3   2023-07-20 [1] RSPM (R 4.3.0)
 generics      0.1.3   2022-07-05 [1] RSPM (R 4.3.0)
 ggplot2     * 3.4.3   2023-08-14 [1] RSPM (R 4.3.0)
 glue          1.6.2   2022-02-24 [1] RSPM (R 4.3.0)
 gtable        0.3.4   2023-08-21 [1] RSPM (R 4.3.0)
 hms           1.1.3   2023-03-21 [1] RSPM (R 4.3.0)
 htmltools     0.5.6   2023-08-10 [1] RSPM (R 4.3.0)
 htmlwidgets   1.6.2   2023-03-17 [1] RSPM (R 4.3.0)
 httpgd        1.3.1   2023-01-30 [1] RSPM
 httpuv        1.6.11  2023-05-11 [1] RSPM (R 4.3.0)
 httr        * 1.4.7   2023-08-15 [1] RSPM (R 4.3.0)
 jsonlite      1.8.7   2023-06-29 [1] RSPM (R 4.3.0)
 knitr         1.43    2023-05-25 [1] RSPM (R 4.3.0)
 labeling      0.4.2   2020-10-20 [1] RSPM (R 4.3.0)
 later         1.3.1   2023-05-02 [1] RSPM (R 4.3.0)
 lattice       0.21-8  2023-04-05 [2] CRAN (R 4.3.1)
 lifecycle     1.0.3   2022-10-07 [1] RSPM (R 4.3.0)
 lubridate   * 1.9.2   2023-02-10 [1] RSPM (R 4.3.0)
 magrittr      2.0.3   2022-03-30 [1] RSPM (R 4.3.0)
 Matrix        1.5-4.1 2023-05-18 [2] CRAN (R 4.3.1)
 memoise       2.0.1   2021-11-26 [1] RSPM (R 4.3.0)
 mgcv          1.8-42  2023-03-02 [2] CRAN (R 4.3.1)
 mime          0.12    2021-09-28 [1] RSPM (R 4.3.0)
 miniUI        0.1.1.1 2018-05-18 [1] RSPM (R 4.3.0)
 munsell       0.5.0   2018-06-12 [1] RSPM (R 4.3.0)
 nlme          3.1-162 2023-01-31 [2] CRAN (R 4.3.1)
 pillar        1.9.0   2023-03-22 [1] RSPM (R 4.3.0)
 pkgbuild      1.4.2   2023-06-26 [1] RSPM (R 4.3.0)
 pkgconfig     2.0.3   2019-09-22 [1] RSPM (R 4.3.0)
 pkgload       1.3.2.1 2023-07-08 [1] RSPM (R 4.3.0)
 prettyunits   1.1.1   2020-01-24 [1] RSPM (R 4.3.0)
 processx      3.8.2   2023-06-30 [1] RSPM (R 4.3.0)
 profvis       0.3.8   2023-05-02 [1] RSPM (R 4.3.0)
 promises      1.2.1   2023-08-10 [1] RSPM (R 4.3.0)
 ps            1.7.5   2023-04-18 [1] RSPM (R 4.3.0)
 purrr       * 1.0.2   2023-08-10 [1] RSPM (R 4.3.0)
 R6            2.5.1   2021-08-19 [1] RSPM (R 4.3.0)
 ragg          1.2.5   2023-01-12 [1] RSPM (R 4.3.0)
 Rcpp          1.0.11  2023-07-06 [1] RSPM (R 4.3.0)
 readr       * 2.1.4   2023-02-10 [1] RSPM (R 4.3.0)
 remotes       2.4.2.1 2023-07-18 [1] RSPM (R 4.3.0)
 rlang         1.1.1   2023-04-28 [1] RSPM (R 4.3.0)
 rstudioapi    0.15.0  2023-07-07 [1] RSPM (R 4.3.0)
 rvest       * 1.0.3   2022-08-19 [1] RSPM (R 4.3.0)
 scales        1.2.1   2022-08-20 [1] RSPM (R 4.3.0)
 selectr       0.4-2   2019-11-20 [1] RSPM (R 4.3.0)
 sessioninfo   1.2.2   2021-12-06 [1] RSPM (R 4.3.0)
 shiny         1.7.5   2023-08-12 [1] RSPM (R 4.3.0)
 stringi       1.7.12  2023-01-11 [1] RSPM (R 4.3.0)
 stringr     * 1.5.0   2022-12-02 [1] RSPM (R 4.3.0)
 systemfonts   1.0.4   2022-02-11 [1] RSPM (R 4.3.0)
 textshaping   0.3.6   2021-10-13 [1] RSPM (R 4.3.0)
 thematic      0.1.3   2023-08-11 [1] RSPM (R 4.3.0)
 tibble      * 3.2.1   2023-03-20 [1] RSPM (R 4.3.0)
 tidyr       * 1.3.0   2023-01-24 [1] RSPM (R 4.3.0)
 tidyselect    1.2.0   2022-10-10 [1] RSPM (R 4.3.0)
 tidyverse   * 2.0.0   2023-02-22 [1] RSPM (R 4.3.0)
 timechange    0.2.0   2023-01-11 [1] RSPM (R 4.3.0)
 tzdb          0.4.0   2023-05-12 [1] RSPM (R 4.3.0)
 urlchecker    1.0.1   2021-11-30 [1] RSPM (R 4.3.0)
 usethis       2.2.2   2023-07-06 [1] RSPM (R 4.3.0)
 utf8          1.2.3   2023-01-31 [1] RSPM (R 4.3.0)
 vctrs         0.6.3   2023-06-14 [1] RSPM (R 4.3.0)
 withr         2.5.0   2022-03-03 [1] RSPM (R 4.3.0)
 xfun          0.40    2023-08-09 [1] RSPM (R 4.3.0)
 xml2          1.3.5   2023-07-06 [1] RSPM (R 4.3.0)
 xtable        1.8-4   2019-04-21 [1] RSPM (R 4.3.0)

 [1] /usr/local/lib/R/site-library
 [2] /usr/local/lib/R/library
</code></pre>
</details>

**Comment by cpsievert** [comment]
Thanks for reporting @jfulponi. Does this happen to fix it?

```r
remotes::install_github("rstudio/thematic#144")
```

**Comment by jfulponi** [comment]
@cpsievert Now works perfectly :D
