### ISSUE TITLE
'Polygon Edge not Found' error with Google fonts, thematic_with_theme(), and renderPlot()

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/thematic#49]
1. From RStudio IDE, Run the following example
```
library(shiny)
library(thematic)
library(showtext)

theme_base <- thematic_theme("white", "red", accent = "purple", font = "auto")
theme_ggplot <- thematic_theme("black", "white", accent = "red", font = "auto")

ui <- fluidPage(
  tags$head(
    tags$link(href="https://fonts.googleapis.com/css?family=Bangers", rel="stylesheet"),
    tags$style(HTML("body{background-color:#F0FFF0; color:#8B008B; font-family:'Bangers'}"))
  ),
  plotOutput("base"),
  plotOutput("ggplot")
)

server <- function(input, output, session) {
  
  output$base <- renderPlot({
    thematic_with_theme(theme_base, {
      plot(1:10, 1:10, col = thematic_get_option("accent"))
    })
  })
  
  output$ggplot <- renderPlot({
    thematic_with_theme(theme_ggplot, {
      ggplot2::qplot(1:10, 1:10, color = 1:10)
    })
  })
  
}

shinyApp(ui, server)
```

2. Open the app in a browser
3. Resize the browser window 

Notice that after resize, the first base plot does not show the text on X and Y axis
Also, during resize, ggplot2 and lattice graphs show an error "polygon edge not found"

<img width="899" alt="thematic_theme_auto_fonts_window_resize" src="https://user-images.githubusercontent.com/5369655/87712684-e66cd700-c75d-11ea-911f-ce7a31eafdb4.png">

**Comment by cpsievert** [comment]
Unfortunately, I'm not sure if we can provide a reasonable fix, but there's a good and easy workaround...just replace `library(showtext)` with `showtext::showtext_auto()`

**Comment by cpsievert** [comment]
Closing since I think we're going to do provide a fix in shiny itself, see https://github.com/rstudio/shiny/issues/2992
