### ISSUE TITLE
Ordered factors always use viridis colors

### ISSUE THREAD

**Issue by Seviks** [rstudio/thematic#59]
When plotting ordered factors, virids colors are used as default (as of ggplot v.3.0.0). Unfortunately there is no new options for (see https://github.com/tidyverse/ggplot2/pull/3828) for scale_fill/colour_ordinal.  I have the same problem with a theme package I build for my company. Is there a better solution than overwritting the scale_fill/colour_ordinal functions? 

Example:
```
thematic_on(bg = "#222222", fg = "white", accent = "#0CE3AC", font = "Oxanium")
ggplot(diamonds, aes(x=color, fill = cut)) +
  geom_bar(position = 'fill') 
ggplot(diamonds, aes(x=color, fill = factor(cut, ordered=FALSE)) +
  geom_bar(position = 'fill') 
```

**Comment by cpsievert** [comment]
>  Is there a better solution than overwritting the scale_fill/colour_ordinal functions?

Not at the moment, but you should consider [filing a feature request in ggplot2](https://github.com/tidyverse/ggplot2/issues/new). I would suggest proposing something like adding a `type` argument to `scale_*_ordinal()` whose value defaults to a global option (similar to `scale_*_continuous()` and `scale_*_discrete()` work)

I'll leave this issue open for the moment, but I don't think it will be worthwhile adding an `ordinal` argument in thematic (for one, it would only have the potential of working for ggplot2, and also, viridis is a good global default for ordinal scales)

**Comment by Seviks** [comment]
Alright, thanks. I thought maybe I've missed something.
