### ISSUE TITLE
Problem with bootstraplib + thematic + rmarkdown.

### ISSUE THREAD

**Issue by porkytin** [rstudio/thematic#63]
I'm trying to create a themed html document using this rmarkdown: 

`
\-\-\-
title: "Thematic demo"
output:
  html_document:
    theme:
      version: 4+3
\-\-\-

\`\`\`{r setup, include=FALSE}
library(bootstraplib)
library(thematic)
library(ggplot2)
bs_theme_new()
bs_theme_base_colors(bg = "#F4F4E2",
                     fg = "#4c4c4c")

bs_theme_accent_colors(primary = "#741336")
\# thematic part
thematic_rmd()
\`\`\`

\#\# {.tabset .tabset-pills}

\#\#\# ggplot2 

\`\`\`{r, message=FALSE, echo = FALSE}
ggplot(diamonds[sample(nrow(diamonds), 1000), ], aes(carat, price),environment = environment()) +
  geom_point(alpha = 0.2) +
  geom_smooth() +
  facet_wrap(~cut) + ggtitle("Diamond price by carat and cut")
\`\`\`

\#\#\# Lattice 

\`\`\`{r echo = FALSE}
lattice::show.settings()
\`\`\`
`
When I run it within RStudio (chunk by chunk) it does not have any problem, but when I press the knitr button or try to create with rmarkdown::render() it rise this error:

`
Quitting from lines 24-28 (Demo.Rmd) 
Error in retrieve_theme_version(theme, "bootstrap") : 
  argument "theme" is missing, with no default
Calls: <Anonymous> ... <Anonymous> -> retrieve_theme_version -> is_bs_theme
`

I have this problem only using both libraries at the same time, I can create a document with no themed graphics (only bootstraplib) and one with only the graphics themed (only thematic with bg,f g and accent arguments in thematic_rmd()), this last one rise lots of warnings though.

Looking at the package's code, it appears to me that has something to do with thematic_get_theme(), I'm running both the latest versions of thematic and bootstraplib installed with remotes package and "rstudio/rmarkdown#1706" in R 4.0.3 in linux. Maybe I'm doing something wrong, so I would appreciate any help, thanks :)

**Comment by cpsievert** [comment]
First, try installing the latest versions: `remotes::install_github(c("rstudio/bootstraplib", "rstudio/rmarkdown#1706"))`

Then, instead of doing:

```r
bs_theme_new()
bs_theme_base_colors(bg = "#F4F4E2",
fg = "#4c4c4c")
bs_theme_accent_colors(primary = "#741336")
```

You can now do:

````
---
title: "Thematic demo"
output:
html_document:
theme:
  version: 4+3
  bg: "#F4F4E2"
  fg: "#4c4c4c"
  primary: "#741336"
---
````

If that doesn't fix it, please reopen the issue!

**Comment by porkytin** [comment]
Hi, first of all, thanks for the quick response. Second, I'm still getting the same error:

`Quitting from lines 29-33 (Demo.Rmd) 
Error in retrieve_theme_version(theme, "bootstrap") : 
  argument "theme" is missing, with no default
Calls: <Anonymous> ... <Anonymous> -> retrieve_theme_version -> is_bs_theme
In addition: Warning message:
'utils::getFromNamespace("bs_theme_get", "bootstraplib")' is deprecated.
Use 'bs_global_get' instead.
See help("Deprecated") 
Execution halted`

Here is my rmarkdown:

~~~
---
title: "Thematic demo"
output:
  html_document:
    theme:
      version: 4+3
      bg: "#F4F4E2"
      fg: "#4c4c4c"
      primary: "#741336"
---
```{r setup, include=FALSE}
library(bootstraplib)
library(thematic)
library(ggplot2)
# bs_theme_new()
# bs_theme_base_colors(bg = "#F4F4E2",
#                      fg = "#4c4c4c")
# 
# bs_theme_accent_colors(primary = "#741336")
# thematic part
thematic_rmd()
```

## {.tabset .tabset-pills}

### ggplot2 

```{r, message=FALSE, echo = FALSE}
ggplot(diamonds[sample(nrow(diamonds), 1000), ], aes(carat, price),environment = environment()) +
  geom_point(alpha = 0.2) +
  geom_smooth() +
  facet_wrap(~cut) + ggtitle("Diamond price by carat and cut")
```

### Lattice 

```{r echo = FALSE}
lattice::show.settings()
```

### Base

```{r echo = FALSE}
pairs(
  iris[,1:4], pch = 19, 
  col = iris$Species, lower.panel = NULL
)
```
~~~

**Comment by porkytin** [comment]
I think I've found the bug and debugged it. I've never made a pull request before so i dont know how to request it, neither how to re-open this issue.

**Comment by cpsievert** [comment]
Are you sure you have the latest versions? I just knitted your Rmd without an issue -- `remotes::install_github(c("rstudio/bootstraplib", "rstudio/rmarkdown#1706"))`

**Comment by porkytin** [comment]
Yes, I'm sure. I'm downloading the individual agreeement to propose the changes that worked for me

**Comment by porkytin** [comment]
I closed the PR becuse it didn't worked as I spected. It worked when I specified the arguments in the chunk like this: 

~~~
```{r setup, include=FALSE}
library(bootstraplib)
library(thematic)
library(ggplot2)
bs_theme_new()
bs_theme_base_colors(bg = "#F4F4E2",
fg = "#4c4c4c")

bs_theme_accent_colors(primary = "#741336")
# thematic part
thematic_rmd()
```
~~~

But still does not work with the parameters specified in the yaml like: 
~~~
---
title: "Thematic demo"
output:
  html_document:
    theme:
      version: 4+3
      bg: "#F4F4E2"
      fg: "#4c4c4c"
      primary: "#741336"
---

So there must be a better solution, the problem i found was in the theme_version() funtion in R/Auto.R
~~~

**Comment by cpsievert** [comment]
Ahh, sorry, I think you also need `remotes::install_github("rstudio/thematic@rc-v0.1.1")` -- I'll work on getting those changes on master this week

**Comment by porkytin** [comment]
`remotes::install_github("rstudio/thematic@rc-v0.1.1")` works fine. It sttill throw error passing themes like:
~~~
theme: flatly
~~~ 

 in the configuration yaml and then using `thematic_rmd()` in the chunks, but I could get arround this using 
~~~
theme:
   version: 4+3
~~~ 
in the yaml part and then setting the theme within the chunk with `bootstrap::bs_global_theme(bootswatch = "flatly")` before calling `thematic_rmd()`

**Comment by cpsievert** [comment]
> It still throw error passing themes like: `theme: flatly`

What do you mean by error? I just tried this and the document knits, but thematic has no effect on the plot colors, which is what I'd expect because `theme: flatly` doesn't use `{bootstraplib}` (and `{bootstraplib}` is required for`{thematic}`'s auto-theming to work in rmarkdown). To put it another way, if you want to use a Bootswatch theme in rmarkdown with {bootstraplib} (and {thematic}'s auto-theming), specify it this way:

````
theme: 
  bootswatch: darkly
````

**Comment by porkytin** [comment]
You are rigth,
~~~
theme: 
  bootswatch: darkly
~~~
that is was I was looking for. So `remotes::install_github("rstudio/thematic@rc-v0.1.1")` Fix my problem completly. Again thank you very much, for the help with my issue and for the thematic library :)
