### ISSUE TITLE
Font availability check sometimes does not work

### ISSUE THREAD

**Issue by wch** [rstudio/thematic#78]
This is the code that checks whether a font is available:
https://github.com/rstudio/thematic/blob/21256e257aff9d435dd1ad3606bea75a81c22574/R/hooks.R#L161-L180

However, it may not give an accurate answer, because R can render graphics asynchronously. For example, in a new R session in the terminal, run this code two times:

```R
tryCatch({
    plot(1, family = "Righteous")
  },
  warning = function(e) {
    message("Caught a warning")
  }
)
```

This is the result:

```
> tryCatch({
+     plot(1, family = "Righteous")
+   },
+   warning = function(e) {
+     message("Caught a warning")
+   }
+ )
> 
There were 36 warnings (use warnings() to see them)
> tryCatch({
+     plot(1, family = "Righteous")
+   },
+   warning = function(e) {
+     message("Caught a warning")
+   }
+ )
Caught a warning
```

The first time, the warnings are **not** caught, but the second time, they are caught. (The logic here is roughly the same as the logic used in thematic.)

For testing, here's an example using grid which does the same thing:

```R
library(grid)
tryCatch({
    grid.newpage()
    grid.text("hello world", 0.5, 0.5, gp=gpar(fontsize=40, fontfamily = "Righteous"))
  },
  warning = function(e) {
    message("got warning")
  }
)
```

**Comment by cpsievert** [comment]
I'm fairly sure this is only ever a problem if this code at the console when a graphics device isn't already open -- and since this code is wrapped in `attempt_with_device(dev_fun, code)` that should never happen...

**Comment by cpsievert** [comment]
For example:

```r
thematic:::attempt_with_device(
  grDevices::png,
  tryCatch({
    plot(1, family = "Righteous")
  },
  warning = function(e) {
    message("Caught a warning")
  }
  )
)
#> Caught a warning
```
