### ISSUE TITLE
Apply RStudio editor themes to help files 

### ISSUE THREAD

**Issue by user63230** [rstudio/thematic#81]
Hi, really like the package! 

I'm not sure if this is possible, but I was wondering could you extent and apply RStudio's editor themes to the help files using thematic? To me it seems this would be easier than what you have already done by applying them to ggplot graphs etc.!

The benefit would be that help files would be easier to read as code within them would be color coded etc. Colin Gillespie had already [achieved](https://stackoverflow.com/questions/64308746/customise-r-help-files-font-colouring) this in his .rprofile but the help files appear color coded in the console as opposed to appearing in the help file viewer so once you start coding again it goes out of view which is really annoying. 

I had already ask this question in another SO post [here](https://stackoverflow.com/questions/64424229/apply-rstudio-editor-themes-to-help-files) but I think the way I was trying to achieve this was over complicated when I see what you package can do. 

thanks!

**Comment by cpsievert** [comment]
Thanks! thematic is focused on static plots, so this wouldn't really fit in the scope of the project, but this might be a nice feature request for http://github.com/rstudio/rstudio or https://github.com/gadenbuie/rsthemes
