### ISSUE TITLE
Fonts section of `custom.Rmd` are exceptionally verbose

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/thematic#88]
The instructions for the Fonts section of the `custom.Rmd` vignette print a lot of warnings regarding missing fonts. It may make sense to hide the warnings in those code chunks for readability purposes. 

https://github.com/rstudio/thematic/blob/95927f4c7de1da62d33a9f825ad91f9bf160420a/vignettes/custom.Rmd#L138

**Comment by cpsievert** [comment]
Fixed by https://github.com/rstudio/thematic/commit/04b2f2455af0c32e77f3915ee260486f74cab9da; although, it is surprising that the default `png` device doesn't appear to work with custom fonts in pkgdown, so I've opened https://github.com/rstudio/thematic/issues/92
